title: Pogosoftware

author: Przemyslaw Pogorzelec
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my blog description
baseurl: ""
url: "https://pogosoftware.net"

permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-paginate

sass:
  style: compressed

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

### PAGINATION
paginate: 3
paginate_path: "/page:num/"

include: 
  - _pages
  - _posts

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME